#!/usr/bin/env python
from __future__ import print_function, division
# http://www-personal.umich.edu/~mejn/computational-physics/

from pylab import scatter, xlabel, ylabel, xlim, ylim, show
from numpy import loadtxt
import matplotlib.pyplot as plt

data = loadtxt("C:\\Users\\Benjamín\\Downloads\\stars.dat", float)
x = data[:, 0]
y = data[:, 1]

fig = plt.figure(figsize = (15, 12))

scatter(x, y)
plt.xlabel("Temperature")
plt.ylabel("Magnitude")
plt.xlim(0, 13000)
plt.ylim(-5, 20)
plt.show(15, 7.5)
